spring.app.jwtSecret=8UzaTSsToPRJVFHf6R8IKShmWEttcLkXF0f+OFjlVHA=
spring.app.jwtExpirationMs=86400000
spring.ecom.app.jwtCookieName=ecom-jwt
spring.security.oauth2.client.registration.google.client-id=322927353224-if589d77f3e4nsom5jej98a4ltitugab.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bakloutichayma8@gmail.com
spring.mail.password=tdsp vqwd hqke dxgn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp   


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project.security=DEBUG
project.image=images/