import m from '../../images/beauty/1.webp';
import mm from '../../images/beauty/3.jpg';
import mmm from '../../images/pet/3.jpg';
import mmmm from '../../images/pet/1.webp';
import mmmmm from '../../images/kids/1.jpg';
import mmmmmm from '../../images/kids/3.jpg';
import mmmmmmm from '../../images/men/1.jpg';
import mmmmmmmm  from '../../images/men/4_.jpg';
import mmmmmmmmm from '../../images/women/2.jpg';
import mmmmmmmmmm  from '../../images/women/4_.jpg';
import mmmmmmmmmmm from '../../images/electronics/1.webp';
import mmmmmmmmmmmm  from '../../images/electronics/3_.jpg';
import mmmmmmmmmmmmm from '../../images/garden/1.jpg';
import mmmmmmmmmmmmmm  from '../../images/garden/1_.webp';
import mmmmmmmmmmmmmmm from '../../images/women/3.jpg';
import mmmmmmmmmmmmmmmm from '../../images/women/5.jpg';
import s from'../../images/men/2.jpg';
import ss from'../../images/men/3.jpg';
import sss from'../../images/men/5.jpg';
import ssss from'../../images/men/6.jpg';
import sssss from'../../images/kids/2.jpg';
import ssssss from'../../images/kids/4.jpg';
import ppppp from'../../images/electronics/2.webp';
import pp from'../../images/beauty/2.jpg';
import pppp from '../../images/pet/2.webp';
import ppp from'../../images/beauty/3.webp';
import light from "../../images/light.jpg";
import sneakers from '../../images/shoes.jpg';
import headphones from "../../images/headphone.jpg";
import backpack from "../../images/pack.jpg";
import smartwatch from "../../images/watch.jpg";
import coffeeMaker from "../../images/coffee.jpg";
import sunglasses from '../../images/glasses.jpg';
import camera from "../../images/camera.jpg";
import plant from "../../images/plants .jpg"

const products = [
  {
    productId: 1,
    image: mmmmmmmmm,
    title: "Ladies Short Sleeve Dress",
    price: 30.00,
    genre: "Women's",
    description: "WEACZZY Women's Summer Short Sleeve Casual Dresses V-Neck Floral Party Dress with Pockets",
    othersph: [mmmmmmmmmmmmmmm],
    colors: ["green","#d500f9"],
    feature: "today",
    stock: 25,
    size: ["S", "M", "L", "XL"],
    discount: 10.00
  },
  {
    productId: 2,
    image: mmmmmmmmmmmmmm,
    title: "Oil Soap Wood Home Cleaner",
    price: 15.22,
    genre: "garden",
    description: "Murphy Oil Soap, Original Formula - 90 fl oz (4PK)",
    othersph: [],
    colors: ["green"],
    feature: "today",
    stock: 50,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 3,
    image: mmmmmmmmmmmmm,
    title: "FREEDOM Garden Hose",
    price: 11.70,
    genre: "garden",
    description: "FREEDOM Garden Hose Reel equipped with 5/8' 100ft, Kink-Free Hybrid Hose, Portable and Wall-Mountable, Lightweight, Easy Setup. Spray Nozzle and Leader Hose Included",
    othersph: [],
    colors: ["purple"],
    feature: "normal",
    stock: 30,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 4,
    image: mmmmmmm,
    title: "Men Leather Formal Shoes",
    price: 220.00,
    genre: "Men's",
    description: "Men's Dress Shoes Genuine Leather Oxfords Luxury Formal Business Suit Shoes with Blake Rapid Stitch",
    othersph: [s,ss],
    colors: ["#000000", "#D2B48C","grey"],
    feature: "normal",
    stock: 20,
    size: [39, 40, 41, 42, 43, 44],
    discount: 10.00,
  },
  {
    productId: 5,
    image: mmmmmmmmmmm,
    title: "Gaming Laptop Pro",
    price: 3500.00,
    genre: "electronics",
    description: "2025 Gaming Laptop 15.6 Inch Laptop Computer with AMD Ryzen 7 5700U Processor, 32GB RAM, 1T SSD, FHD Display 1920*1080P, Windows 11 PRO, WiFi 5, Backlit Keyboard HDMI, for Student, Office, Business",
    othersph: [],
    colors: ["#000000"],
    feature: "weekly",
    stock: 0,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 6,
    image: mmmmmmmmmm,
    title: "Ladies Leather Handbag",
    price: 120.00,
    genre: "Women's",
    description: "HESHE Genuine Leather Purses and Handbags for Women Tote Shoulder Bag Satchel Purse Top Handle Bags Hobo Crossbody Purse",
    othersph: [mmmmmmmmmmmmmmmm],
    colors: ["#763300","#000000"],
    feature: "weekly",
    stock: 18,
    size: ["One Size"],
    discount: 10.00
  },
  {
    productId: 7,
    image: mmmmmmmm,
    title: "Men Stainless Steel Watch",
    price: 450.00,
    genre: "Men's",
    description: "Movado Bold Verso Men's Sport Watch - Swiss Quartz Movement, Stainless Steel Link Bracelet - 5 ATM Water Resistance - Luxury Fashion Timepiece for Him - 42mm",
    othersph: [sss,ssss],
    colors: ["#004d7a"," #EFBF04" ,"#C4C4C4"],
    feature: "weekly",
    stock: 22,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 8,
    image: m,
    title: "Floral Perfume",
    price: 75.00,
    genre: "beauty's",
    description: "Leave In Conditioner Spray, Hair Perfume for Women, Hair Spray Women with Vitamin B5, Moisturizing & Nourishing Damaged Hair, Daily Hair Repair Mist, Floral, 2.5 Fl Oz",
    othersph: [pp],
    colors: ["yellow","orange"],
    feature: "normal",
    stock: 35,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 9,
    image: mmmmmmmmmmmm,
    title: "iPhone New Model",
    price: 499.00,
    genre: "electronics",
    description: "Apple iPhone SE 3rd Gen, 64GB, Midnight - Unlocked (Renewed)",
    othersph: [ppppp],
    colors: ["#000000", "red"],
    feature: "today",
    stock: 12,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 10,
    image: mmmmm,
    title: "Kids Cotton T-Shirt",
    price: 18.90,
    genre: "kid's",
    description: "Family Feeling Boys Short Sleeve Crewneck Kids T-Shirts Top Girls Tee",
    othersph: [sssss],
    colors: ["#000000", "#EDE8D0"],
    feature: "normal",
    stock: 40,
    size: ["XS", "S", "M", "L"],
    discount: 10.00,
  },
  {
    productId: 11,
    image: mm,
    title: "Luxury Lipstick",
    price: 45.00,
    genre: "beauty's",
    description: "LAURA GELLER NEW YORK Italian Marble Sheer Lipstick - Berry Vanilla - Hydrating & Lightweight - Vitamin E & Caster Seed Oil - Cream Finish",
    othersph: [ppp],
    colors: ["#EED9C4", "#7b0000"],
    feature: "weekly",
    stock: 28,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 12,
    image: mmmm,
    title: "Dog Chew Toy",
    price: 25.00,
    genre: "pet's",
    description: "Benebone Natural Rubber Dog Bone Chew Toy, Natural Rubber",
    othersph: [],
    colors: ["#CCFF00"],
    feature: "normal",
    stock: 50,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 13,
    image: mmmmmm,
    title: "Baby Romper Suit",
    price: 50.00,
    genre: "kid's",
    description: "Baby Boy Suit Formal Gentleman Wedding Romper Jumpsuit Set Outfit Tuxedo",
    othersph: [ssssss],
    colors: ["#00d6ff", "#763300"],
    feature: "normal",
    stock: 30,
    size: ["XS", "S", "M"],
    discount: 10.00,
  },
  {
    productId: 14,
    image: mmm,
    title: "Cat Food Bowl",
    price: 15.00,
    genre: "pet's",
    description: "Kitty City Raised Cat Ear Bowls, Small Bowls 2pk (Modern)",
    othersph: [pppp],
    colors: ["#EDE8D0", "#00d6ff"],
    feature: "today",
    stock: 45,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 15,
    image: light,
    title: "Large Pendant Light Ceiling",
    price: 11.70,
    genre: "garden",
    description: "Modern large pendant light for garden or indoor ceiling decoration",
    othersph: [],
    colors: [],
    feature: "weekly",
    stock: 20,
    size: ["One Size"],
    discount: 10.00
  },
  {
    productId: 16,
    image: sneakers,
    title:"Sport Sneakers Unisex",
    price: 120.00,
    genre: "Men's",
    description: "Comfortable sport sneakers suitable for running and casual wear",
    othersph: [],
    colors: [],
    feature: "weekly",
    stock: 25,
    size: [39, 40, 41, 42, 43, 44],
    discount: 10.00,
  },
  {
    productId: 17,
    image: sneakers,
    title: "Sport Sneakers Unisex",
    price: 120.00,
    genre: "Women's",
    description: "Comfortable sport sneakers designed for women, perfect for casual and sport activities",
    othersph: [],
    colors: [],
    feature: "normal",
    stock: 25,
    size: [36, 37, 38, 39, 40, 41],
    discount: 10.00,
  },
  {
    productId: 18,
    image: headphones,
    title: "Wireless Bluetooth Headphones",
    price: 89.90,
    genre: "electronics",
    description: "High-quality wireless Bluetooth headphones with long battery life",
    othersph: [],
    colors: [],
    feature: "weekly",
    stock: 30,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 19,
    image: backpack,
    title: "Waterproof Travel Backpack",
    price: 65.50,
    genre: "Men's",
    description: "Durable and waterproof backpack ideal for travel and outdoor activities",
    othersph: [],
    colors: [],
    feature: "weekly",
    stock: 28,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 20,
    image: smartwatch,
    title: "Smartwatch Series 6",
    price: 350.00,
    genre: "electronics",
    description: "Smartwatch with multiple features including fitness tracking and notifications",
    othersph: [],
    colors: [],
    feature: "weekly",
    stock: 18,
    size: ["One Size"],
    discount:10.00,
  },
  {
    productId: 21,
    image: coffeeMaker,
    title: "Automatic Coffee Machine",
    price: 280.00,
    genre: "electronics",
    description: "Automatic coffee machine for brewing fresh and hot coffee at home",
    othersph: [],
    colors: [],
    feature: "weekly",
    stock: 12,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 22,
    image: sunglasses,
    title: "Polarized Sunglasses",
    price: 45.00,
    genre: "Men's",
    description: "Stylish polarized sunglasses providing UV protection and comfort",
    othersph: [],
    colors: [],
    feature: "weekly",
    stock: 20,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 23,
    image: camera,
    title: "Digital Camera 24MP",
    price: 599.00,
    genre: "electronics",
    description: "High-resolution 24MP digital camera for photography enthusiasts",
    othersph: [],
    colors: [],
    feature: "weekly",
    stock: 15,
    size: ["One Size"],
    discount: 10.00,
  },
  {
    productId: 24,
    image: plant,
    title: "Garden Plant",
    price: 30.00,
    genre: "garden",
    description: "Beautiful and healthy garden plant, perfect for indoor or outdoor decoration.",
    othersph: [],
    colors: [],
    feature: "today",
    stock: 15,
    size: ["One Size"],
    discount: 10.00,
  }
];

export default products;